### ISSUE TITLE
Multiple base statements for identityref not supported ?

### ISSUE THREAD

**Issue by BalazsLengyel** [cmoberg/bottle-yang-extractor-validator#1]
I tried to validate the following:
```
	leaf iref {
		type identityref {
			base x;
			base y ;
		}
```
I got back:

keyword 'base' already given for the second base line.

YANG 1.1 supports multiple base statements for identityrefs, so why do I get the error? Is it just not _yet_  supported or is there some other problem here?

**Comment by cmoberg** [comment]
We use pyang 1.7 to validate the content. And this seems to be from the pyang output. Does this validate cleanly with a local install of (perhaps a newer version of) pyang?

**Comment by cmoberg** [comment]
Then I believe this issue needs to opened with pyang!
