### ISSUE TITLE
Latest Version of ietf-key-chain and ietf-routing-types modules not accessed. 

### ISSUE THREAD

**Issue by aceelindem** [cmoberg/bottle-yang-extractor-validator#6]
ietf-ospf.yang
Pyang Validation

ietf-ospf.yang:992: error: type "bandwidth-ieee-float32" not found in module ietf-routing-types
ietf-ospf.yang:996: error: type "bandwidth-ieee-float32" not found in module ietf-routing-types
ietf-ospf.yang:1009: error: type "bandwidth-ieee-float32" not found in module ietf-routing-types
ietf-ospf.yang:1966: error: identity "crypto-algorithm" not found in module ietf-key-chain

These are clearly in the latest versions of the modules.

**Comment by cmoberg** [comment]
I am (finally) working on a solution for a (much more) frequent update of module versions. Closing this in anticipation of improvement.
